# Generated by Django 5.0.1 on 2024-01-21 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('admin_name', models.CharField(max_length=30)),
                ('admin_email', models.EmailField(max_length=200, unique=True)),
                ('admin_phone', models.CharField(max_length=200)),
                ('admin_address', models.CharField(max_length=2000)),
                ('admin_password', models.CharField(max_length=200)),
                ('admin_profile_pic', models.ImageField(blank=True, default='profile_pics/default.jpeg', upload_to='profile_pics/')),
            ],
        ),
    ]
