# Generated by Django 5.0.1 on 2024-01-20 07:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Catogery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_catogery', models.CharField(max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='farmer',
            name='farmer_profile_pic',
            field=models.ImageField(blank=True, default='profile_pics/default.jpeg', upload_to='profile_pics/'),
        ),
        migrations.CreateModel(
            name='SubCatogery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_subcatogery', models.CharField(max_length=200)),
                ('falls_under_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='farmer.catogery')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=200)),
                ('product_price', models.IntegerField()),
                ('product_quantity', models.IntegerField()),
                ('product_description', models.CharField(max_length=2000)),
                ('product_image', models.ImageField(blank=True, default='product_images/default.jpeg', upload_to='product_images/')),
                ('product_catogery', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='farmer.catogery')),
                ('product_subcatogery', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='farmer.subcatogery')),
            ],
        ),
    ]
