# Generated by Django 5.0.1 on 2024-01-21 12:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('farmer', '0003_unit_cart'),
    ]

    operations = [
        migrations.DeleteModel(
            name='unit',
        ),
    ]
