# Generated by Django 5.0.1 on 2024-01-21 13:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmer', '0005_unit_delete_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=200)),
                ('product_price', models.IntegerField()),
                ('product_quantity', models.IntegerField()),
                ('product_description', models.CharField(max_length=2000)),
                ('product_image', models.ImageField(blank=True, default='product_images/default.jpeg', upload_to='product_images/')),
                ('product_unit', models.CharField(max_length=20)),
                ('product_catogery', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='farmer.catogery')),
                ('product_subcatogery', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='farmer.subcatogery')),
            ],
        ),
        migrations.RemoveField(
            model_name='cart',
            name='farmer',
        ),
        migrations.DeleteModel(
            name='Unit',
        ),
        migrations.DeleteModel(
            name='Cart',
        ),
    ]
