# Generated by Django 5.0.1 on 2024-01-28 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmer', '0006_product_remove_cart_farmer_delete_unit_delete_cart'),
    ]

    operations = [
        migrations.AlterField(
            model_name='farmer',
            name='farmer_profile_pic',
            field=models.ImageField(blank=True, default='profile_pics/default.jpg', upload_to='profile_pics/'),
        ),
    ]
